name: Build steps for the SportTracking project

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  backend_build:
    name: backend_build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: cd sporttracking-backend && mvn -B package --file pom.xml
  frontend_build:
    name: frontend_build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: cd sporttracking-app && yarn install
